Alternate row colors
jncraton/course-search pull request #135
Opened 2024-09-16 18:05 UTC by Jxboss911

Introduces alternating row colors to the course table for improved readability and visual appeal.

2024-09-16 18:21 UTC, jepoorbaugh requested changes
I think you are re-adding all of the prettier files. Could you delete those?

2024-09-16 18:25 UTC, jepoorbaugh reviewed
The colors and styling looks good!

2024-09-17 14:01 UTC, Jxboss911 commented
> I think you are re-adding all of the prettier files. Could you delete those?

Ok i got rid of those files

2024-09-17 14:27 UTC, Peyton3995 requested changes

2024-09-17 14:27 UTC, Peyton3995 commented on package-lock.json
This should not be here. Remove it from your branch before we merge

2024-09-17 14:36 UTC, jepoorbaugh submitted a review, later dismissed
Styles look good!

2024-09-17 14:37 UTC, Jxboss911 commented on package-lock.json
Ok i removed this

2024-09-17 20:22 UTC, Peyton3995 requested changes

2024-09-17 20:22 UTC, Peyton3995 commented on .github/workflows/lint.yml
Please do not include this file in the PR. Do not also make any changes to this file.

2024-09-17 20:22 UTC, Peyton3995 commented on .github/workflows/lint.yml
Apologies for not including this.

2024-09-18 14:45 UTC, jepoorbaugh approved these changes
Looks great!

2024-09-18 15:14 UTC, taigercub commented
looks good to me

2024-09-18 23:27 UTC, Peyton3995 approved these changes
Thank you for removing that file. Seems good to go

2024-09-18 23:28 UTC, merged