Online filter
jncraton/course-search pull request #144
Opened 2024-09-18 04:20 UTC by taigercub

Add functionality to Online Only filter

2024-09-18 12:28 UTC, Peyton3995 requested changes

2024-09-18 12:28 UTC, Peyton3995 commented on package.json
Please do not include anything regarding package.json in your PR.

2024-09-18 15:12 UTC, taigercub commented on package.json
fixed

2024-09-19 00:45 UTC, Peyton3995 approved these changes
Pull this down and it works. Good work

2024-09-19 01:01 UTC, Peyton3995 commented
> Pull this down and it works. Good work

2024-09-19 02:35 UTC, Peyton3995 approved these changes
This actually adds your changes to the git-ignore. This is fine since it will not actually change anything and gives us better coverage.

2024-09-19 02:48 UTC, owenmock22 approved these changes
Looks good

2024-09-19 02:50 UTC, merged